<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.27" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\CareerTracker.Infrastructure\CareerTracker.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\CareerTracker.Kernel\CareerTracker.Kernel.csproj" />
  </ItemGroup>

</Project>
